# Generated by Django 4.0.6 on 2022-08-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тема отзыва'),
        ),
    ]
