# Generated by Django 4.0.6 on 2022-08-01 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0003_feedback_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='HiddenAds',
            fields=[
            ],
            options={
                'verbose_name': 'Скрытое объявление',
                'verbose_name_plural': 'Скрытые объявления',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('flowers.ad',),
        ),
    ]
