# Generated by Django 4.0.6 on 2022-08-01 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0006_purchase_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ('-pk',), 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
    ]
